Updated to dotnet 1.0.1
fsprojects/FsSrGen pull request #11
Opened 2017-03-28 23:54 UTC by ncave

@enricosada Do you think there is a chance to get another release of this (with or without this PR)? It will help keep FCS going until the new .fsproj is supported by VS2017.

2017-03-29 00:33 UTC, cloudRoutine commented
@ncave I can do another one for you, once you've fixed the CI failures

2017-03-29 00:45 UTC, ncave commented
@cloudRoutine Can you do one without this PR? Thanks a lot!

2017-03-29 00:47 UTC, cloudRoutine requested changes

2017-03-29 00:47 UTC, cloudRoutine commented on src/dotnet-fssrgen/project.json
> -    "authors": ["Don Syme","Enrico Sada","Jared Hester"],
you need to move these too, they'll be added to the `.nuspec` generated by `dotnet pack`

2017-03-29 00:47 UTC, cloudRoutine commented on global.json
> -  "projects": [ "src", "test" ]
don't delete this file, specify the dotnet cli version in it

2017-03-29 00:47 UTC, cloudRoutine commented on src/dotnet-fssrgen/dotnet-fssrgen.fsproj
> +    <TargetFramework>netcoreapp1.0</TargetFramework>
should be updated to `netcoreapp1.1` since it supports 12 more platforms

2017-03-29 00:47 UTC, cloudRoutine commented on src/dotnet-fssrgen/dotnet-fssrgen.fsproj
> +    <PackageReference Include="System.Xml.XmlDocument" Version="4.3.0" />
awww crap, this means I gotta go rewrite some code to use `XDocument` instead 😑

2017-03-29 00:58 UTC, cloudRoutine commented
If I'm going to do a release, I'd rather not do another one right after to include stuff that should have gone into the first one.

2017-03-29 01:03 UTC, ncave commented on src/dotnet-fssrgen/project.json
> -    "authors": ["Don Syme","Enrico Sada","Jared Hester"],
Added.

2017-03-29 01:06 UTC, cloudRoutine commented
also you should migrate the other projects too, then I can do a `3.4.0` release for all of them at once. 
plus this is probably the source of the CI failures 😉

2017-03-29 09:59 UTC, enricosada commented
> Do you think there is a chance to get another release of this (with or without this PR)? It will help keep FCS going until the new .fsproj is supported by VS2017

i ❤️ this PR.
but why is needed for FCS? `dotnet-fssrgen` is a cli tool, target should not matter (maybe i am missing something)

2017-03-29 10:09 UTC, ncave commented
@enricosada Perhaps I did not phrase it well, what I tried to say is that FCS dotnet core build target still uses the dotnet-fssrgen cli. The current version on nuget (3.3.0) does not contain the latest master, so I was wondering if it is possible to release another that has the lastest master. This is not really related to this PR which only does the upgrade to 1.0.1.

2017-03-29 10:53 UTC, enricosada commented
ah ok, sure, this is so near, let's just release after this is merged

2017-03-29 19:42 UTC, ncave commented
@cloudRoutine @enricosada
Current state:
- updated all projects (except the test for msbuild task, as the task is already handled by Don, I think)
- packages are successfully created (build CreatePackages)
- for some reason can't add net46 as target
- for some reason can't restore the local package in test/use-dotnet-fssrgen-as-tool

2017-03-30 16:38 UTC, ncave commented
@enricosada

- updated all projects (except the test project for msbuild task, because of #10)
- packages are successfully created (build CreatePackages works)
- tests are now running (build RunTests) but failing to find the resource:
`System.Resources.MissingManifestResourceException : Could not find any resources appropriate for the specified culture or the neutral culture.`

2017-03-30 16:55 UTC, ncave commented
@cloudRoutine @enricosada 
- updated all projects (except the test project for msbuild task, because of #10)
- packages are successfully created (build CreatePackages works)
- tests are now passing (build RunTests) (test for msbuild task is disabled)
(I had to change the [resource name](https://github.com/fsprojects/FsSrGen/pull/11/files#diff-fc665d1970391427f9be649cd2456e2fR391) to make the resources load.)

Can you please review, thanks.

2017-03-30 17:48 UTC, cloudRoutine commented
95-102 in build.fsx are using outdated dotnet cli commands, this is what's causing travis to fail

2017-03-30 17:52 UTC, cloudRoutine approved these changes

2017-03-30 17:53 UTC, cloudRoutine commented
![](http://i.imgur.com/PsuHUNZ.png)

2017-03-30 17:56 UTC, cloudRoutine commented
Other than the last few build config hiccups to straighten out, LGTM.
I'll release a new version once they're both passing. thanks @ncave

2017-03-30 21:11 UTC, ncave commented
@cloudRoutine The only way I could make travis CI pass was to remove the net46 target, please let me know if that's ok.

2017-04-01 19:19 UTC, merged

2017-04-01 21:09 UTC, cloudRoutine commented
@ncave the latest versions are up

2017-04-01 21:10 UTC, ncave commented
@cloudRoutine Thanks!